In [4]:
import pandas as pd
import numpy as np

In [5]:
on_time_linearized = np.load(f'outputs/x_train_on_linearized.npy')
on_time_linearized = on_time_linearized[:1000,:]
on_time_linearized.shape

(1000, 784)

In [6]:
off_time_linearized = np.load(f'outputs/x_train_off_linearized.npy')
off_time_linearized = off_time_linearized[:1000,:]
off_time_linearized.shape

(1000, 784)

In [7]:
df = pd.DataFrame(columns=list(range(1,17))+['on', 'off', 'noise', '???', 'probe_flag'], index=range(off_time_linearized.shape[0]*off_time_linearized.shape[1]))
df

,1,2,3,4,5,6,7,8,9,10,...,12,13,14,15,16,on,off,noise,???,probe_flag
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
for i in range(1,17):
    df.loc[:,i] = True
df.loc[:,'probe_flag'] = False
df.loc[:,'???'] = 50
df.loc[:,'noise'] = 0
df

,1,2,3,4,5,6,7,8,9,10,...,12,13,14,15,16,on,off,noise,???,probe_flag
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783995,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
783996,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
783997,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
783998,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False
783999,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,NaN,NaN,0,50,False

In [9]:
for i, off_sequence in enumerate(off_time_linearized):
    df.loc[range(i*off_time_linearized.shape[1],(i+1)*off_time_linearized.shape[1]),'off'] = off_sequence

In [10]:
for i, on_sequence in enumerate(on_time_linearized):
    df.loc[range(i*on_time_linearized.shape[1],(i+1)*on_time_linearized.shape[1]),'on'] = on_sequence

In [11]:
df.isna().sum()

1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
14            0
15            0
16            0
on            0
off           0
noise         0
???           0
probe_flag    0
dtype: int64

In [13]:
for i, on_sequence in enumerate(on_time_linearized):
    np.savetxt(f'outputs/patterns/linearized/{i}.txt', df.values[range(i*on_time_linearized.shape[1],(i+1)*on_time_linearized.shape[1]), :], fmt='%s', delimiter=', ')
    if i ==100:
        break

In [14]:
df['on']=df['on'].astype(int)
df['off']=df['off'].astype(int)

In [18]:
for i, on_sequence in enumerate(on_time_linearized):
    np.savetxt(f'outputs/patterns/linearized_int/{i}.txt', df.values[range(i*on_time_linearized.shape[1],(i+1)*on_time_linearized.shape[1]), :], fmt='%s', delimiter=', ')
    if i ==100:
        break